### ISSUE TITLE
Error After Update to 2026.3.0

### ISSUE THREAD

**Issue by Kassem-ajjan** [KVSoong/asyncua#15]
Error while setting up asyncua platform for sensor: 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 455, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/asyncua/sensor.py", line 89, in async_setup_platform
    AsyncuaSensor(
    ~~~~~~~~~~~~~^
        coordinator=coordinators[key_coordinator],
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
        unit_of_measurement=val_sensor.get(CONF_NODE_UNIT_OF_MEASUREMENT),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/config/custom_components/asyncua/sensor.py", line 132, in __init__
    self._sensor_data = self._parse_coordinator_data(
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        coordinator_data=coordinator.data
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/config/custom_components/asyncua/sensor.py", line 155, in _parse_coordinator_data
    return coordinator_data.get(self._attr_name)
           ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by User-081** [comment]
I think the error is caused as Home Assistant switched to Python 3.14
See release notes: https://www.home-assistant.io/blog/2026/03/04/release-20263/#running-on-python-314-
The OPC-UA Library supports Python 3.14 starting with Version 1.2b1 - see https://github.com/FreeOpcUa/opcua-asyncio/releases

You can try to manually switch the dependency in the custom_component/asyncua/manifest.json and repleace the line
  "requirements": ["asyncua==1.0.2"],
with
  "requirements": ["asyncua==1.2b1"],
and restart home assistant.
Reading seems to be stable.

**Comment by GrayFarkas** [comment]
I can confirm this issue with a Siemens PLC OPC UA server.

In my case the integration failed during sensor platform setup with:

```text
Error while setting up asyncua platform for sensor: 'NoneType' object has no attribute 'get'

File "/config/custom_components/asyncua/sensor.py", line 155, in _parse_coordinator_data
    return coordinator_data.get(self._attr_name)
AttributeError: 'NoneType' object has no attribute 'get'
```

My YAML was a minimal single-node test:

```yaml
asyncua:
  - name: HVAC_PLC
    url: "opc.tcp://10.10.40.107:4840"
    scan_interval: 1

sensor:
  - platform: asyncua
    nodes:
      - name: "OPC Test FloorHeating Out_Temp"
        unique_id: "opc_test_floorheating_out_temp"
        hub: HVAC_PLC
        nodeid: "ns=4;i=21"
```

The same node was readable with UaExpert, and the PLC diagnostics showed no incoming HA connection while the integration was failing.

The root cause seems to be that `coordinator.data` can still be `None` when `AsyncuaSensor.__init__()` calls `_parse_coordinator_data()`. The initial coordinator refresh happens before platform nodes are added, so there may be no valid data available at entity construction time.

This local patch fixed it for me:

```python
# sensor.py, after adding nodes to the coordinator
coordinators[key_coordinator].add_sensors(sensors=val_coordinator)
await coordinators[key_coordinator].async_request_refresh()
```

and:

```python
# sensor.py
def _parse_coordinator_data(self, coordinator_data):
    if coordinator_data is None:
        return None
    if self._attr_name is None:
        raise ConfigEntryError(
            f"Unable to find {self._attr_name} in coordinator {self.coordinator.name}"
        )
    return coordinator_data.get(self._attr_name)
```

I applied the same pattern to `binary_sensor.py` as well.

After this change:

- the Home Assistant entity was created successfully,
- the PLC diagnostics showed the incoming OPC UA connection from Home Assistant,
- the test node started reading correctly.
